version: "3.0"
services:
  zk1:
    image: zookeeper:3.5.9
    restart: always
    hostname: zk1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 

  kafka1:
    image: confluentinc/cp-kafka:latest.arm64
    depends_on:
    - zk1
    restart: on-failure
    ports:
    - 9091:9091
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP : INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME : INTERNAL
      KAFKA_ADVERTISED_LISTENERS : INTERNAL://kafka1:19091,EXTERNAL://localhost:9091
      KAFKA_ZOOKEEPER_CONNECT : zk1:2181
      KAFKA_BROKER_ID : 1
      BOOTSTRAP_SERVERS : kafka1:19091,kafka2:19092,kafka3:19093


  kafka2:
    image: confluentinc/cp-kafka:latest.arm64
    depends_on:
    - zk1
    restart: on-failure
    ports:
    - "9092:9092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP : INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME : INTERNAL
      KAFKA_ADVERTISED_LISTENERS : INTERNAL://kafka2:19092,EXTERNAL://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT : zk1:2181
      KAFKA_BROKER_ID : 2
      BOOTSTRAP_SERVERS : kafka1:19091,kafka2:19092,kafka3:19093

  kafka3:
    image: confluentinc/cp-kafka:latest.arm64
    depends_on:
    - zk1
    restart: on-failure
    ports:
    - 9093:9093
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP : INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME : INTERNAL
      KAFKA_ADVERTISED_LISTENERS : INTERNAL://kafka3:19093,EXTERNAL://localhost:9093
      KAFKA_ZOOKEEPER_CONNECT : zk1:2181
      KAFKA_BROKER_ID : 3
      BOOTSTRAP_SERVERS : kafka1:19091,kafka2:19092,kafka3:19093

networks:
  default:
    external:
      name: data-playground